---
title: "Survey Stats"
author: "Deanna Elliott"
date: '2022-09-19'
output: html_document
---

```{r setup, include=TRUE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
library(tidyverse)
library(here)
library(ggplot2)
library(ggpubr)
library(broom)
library(AICcmodavg)
library(tidyr)
```

# read in data

```{r}

read_in <- read_csv(here("data", "survey_stats.csv")) %>% 
  janitor::clean_names()

data <- read_in[-c(24, 25, 27, 33, 35, 39, 41, 48, 49, 51, 55, 74, 75, 80, 95, 97, 
                   103, 114, 122, 125, 131, 132, 136), ] 

```

# gender data sets

```{r}

f_data <- data %>% 
  filter(gender == "Woman")

m_data <- data %>% 
  filter(gender == "Man")

mean(f_data$sustainable_options)  # 3.94
mean(m_data$sustainable_options)  # 3.17

mean(f_data$community_benefit_options)  # 4.00
mean(m_data$community_benefit_options)  # 3.45

mean(f_data$difficult_to_find_sustainability)  # 3.39
mean(m_data$difficult_to_find_sustainability)  # 3.14

mean(f_data$difficult_to_find_local_guides)  # 2.72
mean(m_data$difficult_to_find_local_guides)  # 2.62

```


# age

```{r}

age1 <- data %>% filter(age == "18 - 24") 
age2 <- data %>%  filter(age == "25 - 34")
age3 <- data %>%  filter(age == "35 - 44")
age4 <- data %>%  filter(age == "45 - 54")
age5 <- data %>% filter(age == "55+")

mean(age1$sustainable_options)  # 3.44
mean(age2$sustainable_options)  # 3.70
mean(age3$sustainable_options)  # 4.21
mean(age4$sustainable_options)  # 3.63
mean(age5$sustainable_options)  # 4

mean(age1$community_benefit_options)  # 3.84
mean(age2$community_benefit_options)  # 3.86
mean(age3$community_benefit_options)  # 3.89
mean(age4$community_benefit_options)  # 3.63
mean(age5$community_benefit_options)  # 4.17

mean(age1$difficult_to_find_sustainability)  # 3.72
mean(age2$difficult_to_find_sustainability)  # 3.27
mean(age3$difficult_to_find_sustainability)  # 3.05
mean(age4$difficult_to_find_sustainability)  # 3.75
mean(age5$difficult_to_find_sustainability)  # 3.00

mean(age1$difficult_to_find_local_guides)  # 2.84
mean(age2$difficult_to_find_local_guides)  # 2.59
mean(age3$difficult_to_find_local_guides)  # 2.79
mean(age4$difficult_to_find_local_guides)  # 2.75
mean(age5$difficult_to_find_local_guides)  # 2.67



age_groups <- data %>% select(age, sustainable_options, community_benefit_options, difficult_to_find_sustainability, difficult_to_find_local_guides)


# hyp testing

sus_anov <- aov(sustainable_options ~ age, data = age_groups)
summary(sus_anov)

ben_anov <- aov(community_benefit_options ~ age, data = age_groups)
summary(ben_anov)

diff_sus_anov <- aov(difficult_to_find_sustainability ~ age, data = age_groups)
summary(diff_sus_anov)

diff_ben_anov <- aov(difficult_to_find_local_guides ~ age, data = age_groups)
summary(diff_ben_anov)

```

# interactions

```{r}

int.data <- data %>% select(gender, age, relationship, travel_with, trips_per_year, sustainable_options, community_benefit_options, difficult_to_find_sustainability, difficult_to_find_local_guides)

int_sus <- aov(sustainable_options ~ gender*age*relationship*travel_with*trips_per_year, data = int.data)
summary(int_sus)

int_ben <- aov(community_benefit_options ~ gender*age*relationship*travel_with*trips_per_year, data = int.data)
summary(int_ben)

int_sus_diff <- aov(difficult_to_find_sustainability ~ gender*age*relationship*travel_with*trips_per_year, data = int.data)
summary(int_sus_diff)

int_ben_diff <- aov(difficult_to_find_local_guides ~ gender*age*relationship*travel_with*trips_per_year, data = int.data)
summary(int_ben_diff)
```


# travel types

```{r}

cmb_type <- data %>% 
  unite("traveler_type", type:adventure_or_wildlife, remove = TRUE) %>% 
  filter(traveler_type != "NA_NA")

adv <- cmb_type %>% filter(traveler_type %in% c("Both_Adventure", "Adventure Traveler_NA"))

ww <- cmb_type %>% filter(traveler_type %in% c("Both_Wildlife", "Wildlife Watcher_NA"))

counts_gen.type <- cmb_type %>% 
  tabyl(traveler_type, gender)
    # Adv: 56(W), 22(M), 0(NB)
    # WW: 27(W), 7(M), 2(NB)

count_adv_trips <- cmb_type %>% tabyl(traveler_type, trips_per_year)
    # Adv: 2 0-1, 31 2-3, 24 4-5, 21 6+   33(0-3), 45(4-6+)
    # WW: 0 0-1, 22 2-3, 7 4-5, 7 6+      22(2-3), 14(4-6+)
```



